# Generated by `update_singbox.py`
pkgs: {
  "sing-box-prerelease" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-rc.2";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-rc.2";
            hash = "sha256-6SYrBFeXlRGLmjDvRcCrPkAxhu4fjT3cSkTcrW+BRxE=";
          };
          vendorHash = "sha256-/PlwY+ggujfEptSsbuuy/fRu9SxxZFGvvmh7ugzl/yg=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-rc.2"];
        });
  };

  "sing-box-release" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.10";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.10";
            hash = "sha256-HKiTFDNzu42JNra7g+AyTxJ3RuHpvK7ONmKgk2nItT4=";
          };
          vendorHash = "sha256-px90sebov5BbInJtRCGS30fyK3TThNN4XTMtdJhm0Uc=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.10"];
        });
  };

  "sing-box-1_8_10" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.10";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.10";
            hash = "sha256-HKiTFDNzu42JNra7g+AyTxJ3RuHpvK7ONmKgk2nItT4=";
          };
          vendorHash = "sha256-px90sebov5BbInJtRCGS30fyK3TThNN4XTMtdJhm0Uc=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.10"];
        });
  };

  "sing-box-1_8_9" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.9";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.9";
            hash = "sha256-8t+AOTlX34BIftRTZgHwUW3nCPxy8NtbIIocT9YlLbU=";
          };
          vendorHash = "sha256-7FHosBMB5pzsvpHXhWEo8fgD4Rn6+CFoBNFHA+V1e6o=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.9"];
        });
  };

  "sing-box-1_8_8" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.8";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.8";
            hash = "sha256-HbfN9H6mYRZkD1f5CmDSORP29I00u0Ye8l77wrswTE0=";
          };
          vendorHash = "sha256-tOUzshNU6TIjhWVWmlVcw/Ct/V52b+WIJHqs3+weCc0=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.8"];
        });
  };

  "sing-box-1_9_0-rc_2" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-rc.2";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-rc.2";
            hash = "sha256-6SYrBFeXlRGLmjDvRcCrPkAxhu4fjT3cSkTcrW+BRxE=";
          };
          vendorHash = "sha256-/PlwY+ggujfEptSsbuuy/fRu9SxxZFGvvmh7ugzl/yg=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-rc.2"];
        });
  };

  "sing-box-1_9_0-rc_1" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-rc.1";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-rc.1";
            hash = "sha256-/pLITdw4/1FMJ6Nm4Uay1XULbhrsh3gjXnV37aB12Oc=";
          };
          vendorHash = "sha256-EBEEYm28k6DKlBnsHObqCc/0/yynNqlZCs2WZSoRGt0=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-rc.1"];
        });
  };

  "sing-box-1_9_0-beta_17" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-beta.17";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-beta.17";
            hash = "sha256-jr0ZUjxklRX1wjDs7WS132Tfd/3iy+qmt8JoZIS9NIY=";
          };
          vendorHash = "sha256-iMKqPTJGrLlfK2uxxBMFPqpxCH8819wRTucEZuabwMI=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-beta.17"];
        });
  };

  "sing-box-1_9_0-beta_16" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-beta.16";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-beta.16";
            hash = "sha256-xOWNJ0qtpM9rudOoV+L8JHuM2oWFpnFaAfsLun/FhUc=";
          };
          vendorHash = "sha256-wJZ+V/ekACdjF43kBqIszRouAp2YfO5cT2lGditq9IA=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-beta.16"];
        });
  };

  "sing-box-1_9_0-beta_15" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-beta.15";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-beta.15";
            hash = "sha256-2l0tTqTjfUuQWn1nDwyJiydBYuvPgAi2bp8JXBy80Og=";
          };
          vendorHash = "sha256-OXmSO6FkGLMLemq1RWr4LIHKMNPjfy56E5DrObtFZgw=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-beta.15"];
        });
  };
}
