# Generated by `update_singbox.py`
pkgs: {
  "sing-box-prerelease" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.9";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.9";
            hash = "sha256-7dM3iBNAXSs8jaoYRrChi8NzlVtG4slnR3E31lEEU3A=";
          };
          vendorHash = "sha256-UFaRJgqz7eS/L+rumwLX9wh6Xh4/pUVnxM3XzxTGJoM=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.9"];
        });
  };

  "sing-box-release" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.5";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.5";
            hash = "sha256-fW96Hh0eBK8pKkrQP+uA2uaqnZFvZszX2d+VOxKo5Zk=";
          };
          vendorHash = "sha256-4PauMcKpjXtXHJds8MJPH9L+UYPu2fFltP2uUEXtb+o=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.5"];
        });
  };

  "sing-box-1_8_5" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.5";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.5";
            hash = "sha256-fW96Hh0eBK8pKkrQP+uA2uaqnZFvZszX2d+VOxKo5Zk=";
          };
          vendorHash = "sha256-4PauMcKpjXtXHJds8MJPH9L+UYPu2fFltP2uUEXtb+o=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.5"];
        });
  };

  "sing-box-1_8_4" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.4";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.4";
            hash = "sha256-Zn2akHyStq014k4ze3zsqASFnn6VTQ6fu1HdYMBDI1Y=";
          };
          vendorHash = "sha256-L5TFMwhxit4Bm6h6KSEygKxGHbflNa0UQ9lzNqsvuGA=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.4"];
        });
  };

  "sing-box-1_8_2" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.8.2";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.8.2";
            hash = "sha256-+N+3RfWOIM6bZAxmmfG3jMWICWKvOC1CV4hBv8oZjIM=";
          };
          vendorHash = "sha256-NgtZ0z/9X+GWaZqQJMecF/Bxq9u8JKCewgQGSru+EJc=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.8.2"];
        });
  };

  "sing-box-1_9_0-alpha_9" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.9";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.9";
            hash = "sha256-7dM3iBNAXSs8jaoYRrChi8NzlVtG4slnR3E31lEEU3A=";
          };
          vendorHash = "sha256-UFaRJgqz7eS/L+rumwLX9wh6Xh4/pUVnxM3XzxTGJoM=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.9"];
        });
  };

  "sing-box-1_9_0-alpha_8" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.8";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.8";
            hash = "sha256-HR+e4/dCQTB31TCQJTFhCxYUOb4eEzEK/TDaRWL6Qh4=";
          };
          vendorHash = "sha256-wQljYrpgFWEokAkGUM9qusWnnt/GoTNpmp/COSkiAGA=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.8"];
        });
  };

  "sing-box-1_9_0-alpha_7" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.7";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.7";
            hash = "sha256-avPQnmRHL3H07EiBSjKWyRjwpbfbzwFRw7+F1cHWx1I=";
          };
          vendorHash = "sha256-TsV+VIuhlpkChf7PbeQPk36uXdeXvTVxG72qSx0cttk=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.7"];
        });
  };

  "sing-box-1_9_0-alpha_6" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.6";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.6";
            hash = "sha256-IrPbOcs+NN+IR36Qzm72eMFH3IqYirVkv+bK61+FerE=";
          };
          vendorHash = "sha256-kLhRAt6unkvwwCAWddOf6gSHX6TZ4KNCQLTFQr1089A=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.6"];
        });
  };

  "sing-box-1_9_0-alpha_5" = pkgs.sing-box.override {
    buildGoModule = args:
      pkgs.buildGoModule (args
        // {
          version = "1.9.0-alpha.5";
          src = pkgs.fetchFromGitHub {
            owner = "SagerNet";
            repo = "sing-box";
            rev = "v1.9.0-alpha.5";
            hash = "sha256-0mFyqZtskn/sru7qcNJu/2/LwKXarcTopMHtSzv8yvI=";
          };
          vendorHash = "sha256-mGHcrK0p2AsHHDNDjFf/zCG7CoTXnhiWyV0PdNLm3t0=";
          ldflags = ["-X=github.com/sagernet/sing-box/constant.Version=1.9.0-alpha.5"];
        });
  };
}
